### PR TITLE
Release Golo 2.0.0

### PR DESCRIPTION
**Pull request by rlespinasse**
Release notes : http://golo-lang.org/news/2015/01/20/golo-2.0.0/

### CODE REVIEW

**Comment by jponge** [comment]
@rlespinasse thanks, go go go :smile:

**Comment by rlespinasse** [comment]
I need a windows computer before :-)

**Comment by rlespinasse** [comment]
The package is push to http://chocolatey.org

Now, we need to wait the review 
> Moderators typically review a package within 1-3 business days.

After that, this PR will be merge to the master

**Comment by rlespinasse** [comment]
The package is approved by Chocolatey https://chocolatey.org/packages/golo/2.0.0

**Pull request merged**
